//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureDirect.WCFService
{
  using System;
  using System.Runtime.Serialization;
  using System.ServiceModel;
  using System.ServiceModel.Channels;


  [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContract", Namespace="http://schemas.datacontract.org/2004/07/PictureDirect.WCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PictureDirect.WCFService.LoginResponseContract))]
    public partial class ResponseContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PictureDirect.WCFService.DemandesContract ResponseField;
        
        private int ResultCodeField;
        
        private string ResultInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PictureDirect.WCFService.DemandesContract Response
        {
            get
            {
                return this.ResponseField;
            }
            set
            {
                this.ResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultInfo
        {
            get
            {
                return this.ResultInfoField;
            }
            set
            {
                this.ResultInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DemandesContract", Namespace="http://schemas.datacontract.org/2004/07/PictureDirect.WCF")]
    public partial class DemandesContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<PictureDirect.WCFService.DemandeContract> DemandesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PictureDirect.WCFService.DemandeContract> Demandes
        {
            get
            {
                return this.DemandesField;
            }
            set
            {
                this.DemandesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponseContract", Namespace="http://schemas.datacontract.org/2004/07/PictureDirect.WCF")]
    public partial class LoginResponseContract : PictureDirect.WCFService.ResponseContract
    {
        
        private bool BlockWrongVersionField;
        
        private int MaxNumberOfPicturesField;
        
        private string WcfVersionField;
        
        private string WrongVersionMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BlockWrongVersion
        {
            get
            {
                return this.BlockWrongVersionField;
            }
            set
            {
                this.BlockWrongVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberOfPictures
        {
            get
            {
                return this.MaxNumberOfPicturesField;
            }
            set
            {
                this.MaxNumberOfPicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WcfVersion
        {
            get
            {
                return this.WcfVersionField;
            }
            set
            {
                this.WcfVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WrongVersionMessage
        {
            get
            {
                return this.WrongVersionMessageField;
            }
            set
            {
                this.WrongVersionMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DemandeContract", Namespace="http://schemas.datacontract.org/2004/07/PictureDirect.WCF")]
    public partial class DemandeContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<PictureDirect.WCFService.ActionContract> ActionsField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PictureDirect.WCFService.ActionContract> Actions
        {
            get
            {
                return this.ActionsField;
            }
            set
            {
                this.ActionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionContract", Namespace="http://schemas.datacontract.org/2004/07/PictureDirect.WCF")]
    public partial class ActionContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictureDirect.WCFService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        PictureDirect.WCFService.LoginResponseContract Login(int numUser, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.IAsyncResult BeginLogin(int numUser, string username, string password, System.AsyncCallback callback, object asyncState);
        
        PictureDirect.WCFService.LoginResponseContract EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDemandes", ReplyAction="http://tempuri.org/IService/GetDemandesResponse")]
        PictureDirect.WCFService.ResponseContract GetDemandes(int numUser);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetDemandes", ReplyAction="http://tempuri.org/IService/GetDemandesResponse")]
        System.IAsyncResult BeginGetDemandes(int numUser, System.AsyncCallback callback, object asyncState);
        
        PictureDirect.WCFService.ResponseContract EndGetDemandes(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis l'opération UploadPicture n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadPicture", ReplyAction="http://tempuri.org/IService/UploadPictureResponse")]
        PictureDirect.WCFService.UploadPictureResponse UploadPicture(PictureDirect.WCFService.RemoteFileInfoContract request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/UploadPicture", ReplyAction="http://tempuri.org/IService/UploadPictureResponse")]
        System.IAsyncResult BeginUploadPicture(PictureDirect.WCFService.RemoteFileInfoContract request, System.AsyncCallback callback, object asyncState);
        
        PictureDirect.WCFService.UploadPictureResponse EndUploadPicture(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfoContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfoContract
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int ActionId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Description;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int NumUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int PictureId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfoContract()
        {
        }
        
        public RemoteFileInfoContract(int ActionId, string Description, long Length, int NumUser, int PictureId, System.IO.Stream FileByteStream)
        {
            this.ActionId = ActionId;
            this.Description = Description;
            this.Length = Length;
            this.NumUser = NumUser;
            this.PictureId = PictureId;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadPictureResponse
    {
        
        public UploadPictureResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PictureDirect.WCFService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public PictureDirect.WCFService.LoginResponseContract Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((PictureDirect.WCFService.LoginResponseContract)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDemandesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public GetDemandesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public PictureDirect.WCFService.ResponseContract Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((PictureDirect.WCFService.ResponseContract)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PictureDirect.WCFService.IService>, PictureDirect.WCFService.IService
    {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDemandesDelegate;
        
        private EndOperationDelegate onEndGetDemandesDelegate;
        
        private System.Threading.SendOrPostCallback onGetDemandesCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadPictureDelegate;
        
        private EndOperationDelegate onEndUploadPictureDelegate;
        
        private System.Threading.SendOrPostCallback onUploadPictureCompletedDelegate;
        
        public ServiceClient()
        {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

    protected override IService CreateChannel()
    {
      return new ServiceChannel(this);
    }


    private class ServiceChannel : ChannelBase<IService>, IService
    {
      public ServiceChannel(ClientBase<IService> client) :
          base(client)
      {
      }

      //utiliser (typeMethode)base.BeginInvoke("CommandeDansLaMethode", tous les arguments)
      //Si Methode déjà faite, réutiliser la méthode similaire au dessus et utiliser le résultat (tu te débrouille)

      public IAsyncResult BeginGetDemandes(int numUser, AsyncCallback callback, object asyncState)
      {
        return (IAsyncResult)base.BeginInvoke("GetDemandes", new object[] { numUser }, callback, asyncState);
      }

      public IAsyncResult BeginLogin(int numUser, string username, string password, AsyncCallback callback, object asyncState)
      {
        return (IAsyncResult)base.BeginInvoke("Login", new object[] { numUser, username, password }, callback, asyncState);
      }

      public IAsyncResult BeginUploadPicture(RemoteFileInfoContract request, AsyncCallback callback, object asyncState)
      {
        return (IAsyncResult)base.BeginInvoke("Login", new object[] { request }, callback, asyncState);
      }

      public ResponseContract EndGetDemandes(IAsyncResult result)
      {
        return (ResponseContract)base.EndInvoke("GetDemandes", new object[] { }, result);
      }

      public LoginResponseContract EndLogin(IAsyncResult result)
      {
        return (LoginResponseContract)base.EndInvoke("Login", new object[] { }, result);
      }

      public UploadPictureResponse EndUploadPicture(IAsyncResult result)
      {
        return (UploadPictureResponse)base.EndInvoke("UploadPicture", new object[] { }, result);
      }

      public ResponseContract GetDemandes(int numUser)
      {
        var begDemandes = (IAsyncResult)base.BeginInvoke("GetDemandes", new object[] { numUser }, null, null);
        return (ResponseContract)base.EndInvoke("GetDemandes", new object[] { }, begDemandes);
      }
      public LoginResponseContract Login(int numUser, string username, string password)
      {
        var begLogin = (IAsyncResult)base.BeginInvoke("Login", new object[] { numUser, username, password }, null, null);
        return (LoginResponseContract)base.EndInvoke("Login", new object[] { }, begLogin);
      }
      public UploadPictureResponse UploadPicture(RemoteFileInfoContract request)
      {
        var upPic = (IAsyncResult)base.BeginInvoke("UploadPicture", new object[] { request }, null, null);
        return (UploadPictureResponse)base.EndInvoke("UploadPicture", new object[] { }, upPic);
      }
    }

    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<GetDemandesCompletedEventArgs> GetDemandesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadPictureCompleted;
        
        public PictureDirect.WCFService.LoginResponseContract Login(int numUser, string username, string password)
        {
            return base.Channel.Login(numUser, username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogin(int numUser, string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginLogin(numUser, username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PictureDirect.WCFService.LoginResponseContract EndLogin(System.IAsyncResult result)
        {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int numUser = ((int)(inValues[0]));
            string username = ((string)(inValues[1]));
            string password = ((string)(inValues[2]));
            return this.BeginLogin(numUser, username, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result)
        {
            PictureDirect.WCFService.LoginResponseContract retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state)
        {
            if ((this.LoginCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(int numUser, string username, string password)
        {
            this.LoginAsync(numUser, username, password, null);
        }
        
        public void LoginAsync(int numUser, string username, string password, object userState)
        {
            if ((this.onBeginLoginDelegate == null))
            {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null))
            {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null))
            {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        numUser,
                        username,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        public PictureDirect.WCFService.ResponseContract GetDemandes(int numUser)
        {
            return base.Channel.GetDemandes(numUser);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDemandes(int numUser, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetDemandes(numUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PictureDirect.WCFService.ResponseContract EndGetDemandes(System.IAsyncResult result)
        {
            return base.Channel.EndGetDemandes(result);
        }
        
        private System.IAsyncResult OnBeginGetDemandes(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int numUser = ((int)(inValues[0]));
            return this.BeginGetDemandes(numUser, callback, asyncState);
        }
        
        private object[] OnEndGetDemandes(System.IAsyncResult result)
        {
            PictureDirect.WCFService.ResponseContract retVal = this.EndGetDemandes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDemandesCompleted(object state)
        {
            if ((this.GetDemandesCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDemandesCompleted(this, new GetDemandesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDemandesAsync(int numUser)
        {
            this.GetDemandesAsync(numUser, null);
        }
        
        public void GetDemandesAsync(int numUser, object userState)
        {
            if ((this.onBeginGetDemandesDelegate == null))
            {
                this.onBeginGetDemandesDelegate = new BeginOperationDelegate(this.OnBeginGetDemandes);
            }
            if ((this.onEndGetDemandesDelegate == null))
            {
                this.onEndGetDemandesDelegate = new EndOperationDelegate(this.OnEndGetDemandes);
            }
            if ((this.onGetDemandesCompletedDelegate == null))
            {
                this.onGetDemandesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDemandesCompleted);
            }
            base.InvokeAsync(this.onBeginGetDemandesDelegate, new object[] {
                        numUser}, this.onEndGetDemandesDelegate, this.onGetDemandesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PictureDirect.WCFService.UploadPictureResponse PictureDirect.WCFService.IService.UploadPicture(PictureDirect.WCFService.RemoteFileInfoContract request)
        {
            return base.Channel.UploadPicture(request);
        }
        
        public void UploadPicture(int ActionId, string Description, long Length, int NumUser, int PictureId, System.IO.Stream FileByteStream)
        {
            PictureDirect.WCFService.RemoteFileInfoContract inValue = new PictureDirect.WCFService.RemoteFileInfoContract();
            inValue.ActionId = ActionId;
            inValue.Description = Description;
            inValue.Length = Length;
            inValue.NumUser = NumUser;
            inValue.PictureId = PictureId;
            inValue.FileByteStream = FileByteStream;
            PictureDirect.WCFService.UploadPictureResponse retVal = ((PictureDirect.WCFService.IService)(this)).UploadPicture(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PictureDirect.WCFService.IService.BeginUploadPicture(PictureDirect.WCFService.RemoteFileInfoContract request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginUploadPicture(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUploadPicture(int ActionId, string Description, long Length, int NumUser, int PictureId, System.IO.Stream FileByteStream, System.AsyncCallback callback, object asyncState)
        {
            PictureDirect.WCFService.RemoteFileInfoContract inValue = new PictureDirect.WCFService.RemoteFileInfoContract();
            inValue.ActionId = ActionId;
            inValue.Description = Description;
            inValue.Length = Length;
            inValue.NumUser = NumUser;
            inValue.PictureId = PictureId;
            inValue.FileByteStream = FileByteStream;
            return ((PictureDirect.WCFService.IService)(this)).BeginUploadPicture(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PictureDirect.WCFService.UploadPictureResponse PictureDirect.WCFService.IService.EndUploadPicture(System.IAsyncResult result)
        {
            return base.Channel.EndUploadPicture(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndUploadPicture(System.IAsyncResult result)
        {
            PictureDirect.WCFService.UploadPictureResponse retVal = ((PictureDirect.WCFService.IService)(this)).EndUploadPicture(result);
        }
        
        private System.IAsyncResult OnBeginUploadPicture(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int ActionId = ((int)(inValues[0]));
            string Description = ((string)(inValues[1]));
            long Length = ((long)(inValues[2]));
            int NumUser = ((int)(inValues[3]));
            int PictureId = ((int)(inValues[4]));
            System.IO.Stream FileByteStream = ((System.IO.Stream)(inValues[5]));
            return this.BeginUploadPicture(ActionId, Description, Length, NumUser, PictureId, FileByteStream, callback, asyncState);
        }
        
        private object[] OnEndUploadPicture(System.IAsyncResult result)
        {
            this.EndUploadPicture(result);
            return null;
        }
        
        private void OnUploadPictureCompleted(object state)
        {
            if ((this.UploadPictureCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadPictureCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadPictureAsync(int ActionId, string Description, long Length, int NumUser, int PictureId, System.IO.Stream FileByteStream)
        {
            this.UploadPictureAsync(ActionId, Description, Length, NumUser, PictureId, FileByteStream, null);
        }
        
        public void UploadPictureAsync(int ActionId, string Description, long Length, int NumUser, int PictureId, System.IO.Stream FileByteStream, object userState)
        {
            if ((this.onBeginUploadPictureDelegate == null))
            {
                this.onBeginUploadPictureDelegate = new BeginOperationDelegate(this.OnBeginUploadPicture);
            }
            if ((this.onEndUploadPictureDelegate == null))
            {
                this.onEndUploadPictureDelegate = new EndOperationDelegate(this.OnEndUploadPicture);
            }
            if ((this.onUploadPictureCompletedDelegate == null))
            {
                this.onUploadPictureCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadPictureCompleted);
            }
            base.InvokeAsync(this.onBeginUploadPictureDelegate, new object[] {
                        ActionId,
                        Description,
                        Length,
                        NumUser,
                        PictureId,
                        FileByteStream}, this.onEndUploadPictureDelegate, this.onUploadPictureCompletedDelegate, userState);
        }
    }
}
