//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozartControls.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MozartControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité EMALEC.
        /// </summary>
        public static string act_emalec {
            get {
                return ResourceManager.GetString("act_emalec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        public static string activite {
            get {
                return ResourceManager.GetString("activite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add_32 {
            get {
                object obj = ResourceManager.GetObject("add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les contacts.
        /// </summary>
        public static string afficher_contacts {
            get {
                return ResourceManager.GetString("afficher_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les contacts archivés.
        /// </summary>
        public static string afficher_contacts_archives {
            get {
                return ResourceManager.GetString("afficher_contacts_archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année.
        /// </summary>
        public static string Annee {
            get {
                return ResourceManager.GetString("Annee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à archivés.
        /// </summary>
        public static string archivees {
            get {
                return ResourceManager.GetString("archivees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à archivées.
        /// </summary>
        public static string archives {
            get {
                return ResourceManager.GetString("archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client(s) Rattaché(s).
        /// </summary>
        public static string clientsRattaches {
            get {
                return ResourceManager.GetString("clientsRattaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à APE.
        /// </summary>
        public static string codeAPE {
            get {
                return ResourceManager.GetString("codeAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actif.
        /// </summary>
        public static string col_Actif {
            get {
                return ResourceManager.GetString("col_Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string col_Action {
            get {
                return ResourceManager.GetString("col_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client.
        /// </summary>
        public static string col_Client {
            get {
                return ResourceManager.GetString("col_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string col_Date {
            get {
                return ResourceManager.GetString("col_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;arrivée.
        /// </summary>
        public static string col_DateArr {
            get {
                return ResourceManager.GetString("col_DateArr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de sortie.
        /// </summary>
        public static string col_DateSortie {
            get {
                return ResourceManager.GetString("col_DateSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devis.
        /// </summary>
        public static string col_Devis {
            get {
                return ResourceManager.GetString("col_Devis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DI.
        /// </summary>
        public static string col_DI {
            get {
                return ResourceManager.GetString("col_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat.
        /// </summary>
        public static string col_Etat {
            get {
                return ResourceManager.GetString("col_Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filiale.
        /// </summary>
        public static string col_Filiale {
            get {
                return ResourceManager.GetString("col_Filiale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure d&apos;arrivée.
        /// </summary>
        public static string col_HeureArr {
            get {
                return ResourceManager.GetString("col_HeureArr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de sortie.
        /// </summary>
        public static string col_HeureSortie {
            get {
                return ResourceManager.GetString("col_HeureSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé.
        /// </summary>
        public static string col_libelle {
            get {
                return ResourceManager.GetString("col_libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matériel.
        /// </summary>
        public static string col_Materiel {
            get {
                return ResourceManager.GetString("col_Materiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mois.
        /// </summary>
        public static string col_Mois {
            get {
                return ResourceManager.GetString("col_Mois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N°.
        /// </summary>
        public static string col_No {
            get {
                return ResourceManager.GetString("col_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays.
        /// </summary>
        public static string col_Pays {
            get {
                return ResourceManager.GetString("col_Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remarque.
        /// </summary>
        public static string col_Remarque {
            get {
                return ResourceManager.GetString("col_Remarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Série.
        /// </summary>
        public static string col_Serie {
            get {
                return ResourceManager.GetString("col_Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site.
        /// </summary>
        public static string col_Site {
            get {
                return ResourceManager.GetString("col_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TVA Intra.
        /// </summary>
        public static string col_TVAIntra {
            get {
                return ResourceManager.GetString("col_TVAIntra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string col_Type {
            get {
                return ResourceManager.GetString("col_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UE / Tiers UE.
        /// </summary>
        public static string col_UETiersUE {
            get {
                return ResourceManager.GetString("col_UETiersUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string col_Ville {
            get {
                return ResourceManager.GetString("col_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborateur.
        /// </summary>
        public static string collaborateur {
            get {
                return ResourceManager.GetString("collaborateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires.
        /// </summary>
        public static string Commentaires {
            get {
                return ResourceManager.GetString("Commentaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commercial.
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commercial de suivi.
        /// </summary>
        public static string commercial_suivi {
            get {
                return ResourceManager.GetString("commercial_suivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créateur.
        /// </summary>
        public static string createur {
            get {
                return ResourceManager.GetString("createur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D. Action.
        /// </summary>
        public static string d_action {
            get {
                return ResourceManager.GetString("d_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D. RDV.
        /// </summary>
        public static string D_RDV {
            get {
                return ResourceManager.GetString("D_RDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D. Relance.
        /// </summary>
        public static string D_Relance {
            get {
                return ResourceManager.GetString("D_Relance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAS EMALEC.
        /// </summary>
        public static string DAS_Emalec {
            get {
                return ResourceManager.GetString("DAS_Emalec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 1ière DI.
        /// </summary>
        public static string date_1iere_DI {
            get {
                return ResourceManager.GetString("date_1iere_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Création.
        /// </summary>
        public static string date_creation {
            get {
                return ResourceManager.GetString("date_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Démarrage contrat.
        /// </summary>
        public static string date_demarrage_contrat {
            get {
                return ResourceManager.GetString("date_demarrage_contrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Modif.
        /// </summary>
        public static string date_modif {
            get {
                return ResourceManager.GetString("date_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Réponse.
        /// </summary>
        public static string date_reponse {
            get {
                return ResourceManager.GetString("date_reponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Défensif.
        /// </summary>
        public static string defensif {
            get {
                return ResourceManager.GetString("defensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete_32 {
            get {
                object obj = ResourceManager.GetObject("delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département.
        /// </summary>
        public static string departement {
            get {
                return ResourceManager.GetString("departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développement.
        /// </summary>
        public static string developpement {
            get {
                return ResourceManager.GetString("developpement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emplacement.
        /// </summary>
        public static string Emplacement {
            get {
                return ResourceManager.GetString("Emplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estimatif global.
        /// </summary>
        public static string estimatif_global {
            get {
                return ResourceManager.GetString("estimatif_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filiale concernée.
        /// </summary>
        public static string filiale_concernee {
            get {
                return ResourceManager.GetString("filiale_concernee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forfaitaire préventif.
        /// </summary>
        public static string forfaitaire_preventif {
            get {
                return ResourceManager.GetString("forfaitaire_preventif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fourniture.
        /// </summary>
        public static string Fourniture {
            get {
                return ResourceManager.GetString("Fourniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion commerciale des prospects.
        /// </summary>
        public static string gest_com_prospect {
            get {
                return ResourceManager.GetString("gest_com_prospect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dans .
        /// </summary>
        public static string Global_dans {
            get {
                return ResourceManager.GetString("Global_dans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string Global_erreur {
            get {
                return ResourceManager.GetString("Global_erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe.
        /// </summary>
        public static string Groupe {
            get {
                return ResourceManager.GetString("Groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modificateur.
        /// </summary>
        public static string modificateur {
            get {
                return ResourceManager.GetString("modificateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif.
        /// </summary>
        public static string motif {
            get {
                return ResourceManager.GetString("motif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du N° TVA Intra n&apos;est pas conforme.
        /// </summary>
        public static string msg_Code_TVA_intra_invalide {
            get {
                return ResourceManager.GetString("msg_Code_TVA_intra_invalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le libellé de l&apos;offre !.
        /// </summary>
        public static string msg_enter_libelle_offre {
            get {
                return ResourceManager.GetString("msg_enter_libelle_offre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un numéro de TVA intra est obligatoire.
        /// </summary>
        public static string msg_enter_TVA {
            get {
                return ResourceManager.GetString("msg_enter_TVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un pays doit être sélectionné.
        /// </summary>
        public static string msg_Select_Pays {
            get {
                return ResourceManager.GetString("msg_Select_Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez renseigner le commercial de suivi..
        /// </summary>
        public static string must_fill_com_suivi {
            get {
                return ResourceManager.GetString("must_fill_com_suivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb Sites.
        /// </summary>
        public static string nb_sites {
            get {
                return ResourceManager.GetString("nb_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string non {
            get {
                return ResourceManager.GetString("non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Origine de contact.
        /// </summary>
        public static string orig_de_contact {
            get {
                return ResourceManager.GetString("orig_de_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string oui {
            get {
                return ResourceManager.GetString("oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays d&apos;intervention.
        /// </summary>
        public static string pays_inter {
            get {
                return ResourceManager.GetString("pays_inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Périmètre pays.
        /// </summary>
        public static string perimetre_pays {
            get {
                return ResourceManager.GetString("perimetre_pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à % de chance de gain.
        /// </summary>
        public static string pourc_chance_gain {
            get {
                return ResourceManager.GetString("pourc_chance_gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priorité.
        /// </summary>
        public static string priorite {
            get {
                return ResourceManager.GetString("priorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prospecteur.
        /// </summary>
        public static string Prospecteur {
            get {
                return ResourceManager.GetString("Prospecteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment archiver ce prospect ?.
        /// </summary>
        public static string quest_archi_prospect {
            get {
                return ResourceManager.GetString("quest_archi_prospect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous archiver ce contact ?.
        /// </summary>
        public static string quest_archiver_contact {
            get {
                return ResourceManager.GetString("quest_archiver_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RDV Réalisé.
        /// </summary>
        public static string RDV_Realise {
            get {
                return ResourceManager.GetString("RDV_Realise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement effectué..
        /// </summary>
        public static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur Client.
        /// </summary>
        public static string secteur_client {
            get {
                return ResourceManager.GetString("secteur_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionné.
        /// </summary>
        public static string selected {
            get {
                return ResourceManager.GetString("selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Société.
        /// </summary>
        public static string societe {
            get {
                return ResourceManager.GetString("societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type d’offre.
        /// </summary>
        public static string type_offre {
            get {
                return ResourceManager.GetString("type_offre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visiteur.
        /// </summary>
        public static string visiteur {
            get {
                return ResourceManager.GetString("visiteur", resourceCulture);
            }
        }
    }
}
