//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozartLib
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;

  [Table("TPAYS")]
  public partial class TPAYS
  {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int NPAYSNUM { get; set; }
    public string VPAYSNOM { get; set; }
    public string VPAYSABR { get; set; }
    public Nullable<decimal> NPAYSTVA { get; set; }
    public string CPAYSPRIXCLI { get; set; }
    public string VPAYSNUMTVA { get; set; }
    public string VDEVISE { get; set; }
    public string VLANGUEDEFAUT { get; set; }
    public string VLANGUEABR { get; set; }
    public string NPAYSUE { get; set; }
  }
}
