//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozartLib
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;

  [Table("TREF_BANQUE")]
  public partial class TREF_BANQUE
  {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int NIDBANQUE { get; set; }
    public string VBANQUENOM { get; set; }
    public string VBANQUEIBAN { get; set; }
    public string VBANQUEBIC { get; set; }
    public string VSOCIETE { get; set; }
    public Nullable<bool> BBANQUEDEFAULT { get; set; }
  }
}
