//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozartLib
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;
  using System.Data;

  [Table("TREF_TYPECONTRAT")]
  public partial class TREF_TYPECONTRAT
  {
    [Key]
    [Column(Order = 1)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int NTYPECONTRAT { get; set; }
    [Key]
    [Column(Order = 2)]
    public string LANGUE { get; set; }
    public string VTYPECONTRAT { get; set; }
    public string VCONTRATCOUR { get; set; }
    public string CACTIF { get; set; }
    public int? NTYPEDOMAINE { get; set; }
  }
}
