//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozartLib
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;

  [Table("TREF_SECTEUR")]
  public partial class TREF_SECTEUR
  {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int NSECTEUR { get; set; }
    public string VSECTEUR { get; set; }
    public string VSOUSACTIVITE { get; set; }
    public string VCODEAPE { get; set; }
    public string LANGUE { get; set; }
  }
}
